name: member360
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#IOS
#version: 1.0.0+7
#Android
version: 2.0.84+93

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  adaptive_theme: ^3.4.1
  animated_bottom_navigation_bar: ^1.1.0
  animations: ^2.0.8
  app_settings: ^6.1.1
  auto_route: ^10.0.1
  bloc: ^9.0.0
  cached_network_image: ^3.3.0
  calendar_timeline_sbk: ^1.1.7
  collection: ^1.17.2
  country_calling_code_picker: ^2.0.1
  cupertino_icons: ^1.0.6
  device_info_plus: ^11.3.0
  dio: ^5.1.1
  equatable: ^2.0.5
  file_picker: ^10.1.9
  firebase_analytics: ^12.0.2
  firebase_core: ^4.1.1
  firebase_crashlytics: ^5.0.2
  firebase_messaging: ^16.0.2
  flutter:
    sdk: flutter
  flutter_agenda: ^5.0.5
  flutter_bloc: ^9.1.0
  flutter_blue_plus: ^2.0.0
  flutter_easyloading: ^3.0.5
  flutter_keyboard_visibility: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^19.4.2
  flutter_localizations:
    sdk: flutter
  flutter_rounded_date_picker: ^3.0.4
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^4.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  flutter_switch: ^0.3.2
  flutter_week_view: ^1.4.3
  fluttertoast: ^8.2.4
  freezed: ^3.0.6
  freezed_annotation: ^3.1.0
  geocode: ^1.0.3
  get: ^4.6.6
  get_it: ^8.0.3
  google_fonts: ^6.1.0
  hand_signature: ^3.0.3
  image_picker: ^1.2.0
  infinite_scroll_pagination: ^5.0.0
  injectable: ^2.3.2
  internet_connectivity_checker: ^1.0.2
  intl: ^0.19.0
  intl_utils: ^2.8.6
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  new_version_plus: any
  open_file: ^3.5.7
  package_info_plus: ^8.3.1
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  permission_handler: ^12.0.1
  pin_code_fields: ^8.0.1
  process_run: ^1.2.2+1
  share_plus: ^12.0.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  simple_connection_checker: ^0.3.4
  syncfusion_flutter_calendar: ^29.1.38
  tf_dio_cache: ^1.0.2
  url_launcher: ^6.3.2
  widget_and_text_animator: ^1.1.5

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1

dependency_overrides:
  intl: any

flutter_intl:
  main_locale: en
  enabled: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#dd2d92"
  image_path: "assets/images/logo-release.png"
  adaptive_icon_foreground: "assets/images/logo-release.png"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
