import 'dart:math';

import 'package:auto_route/auto_route.dart';
// import 'package:dynamic_timeline/dynamic_timeline.dart';
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter/services.dart';
import 'package:flutter_agenda/flutter_agenda.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_week_view/flutter_week_view.dart';
import 'package:intl/intl.dart' as intl;
import 'package:member360/core/bloc/base_bloc/base_bloc.dart';
import 'package:member360/core/bloc/base_bloc/base_state.dart';
import 'package:member360/core/bloc/value_state_manager/value_state_manager_import.dart';
import 'package:member360/core/constants/gaps.dart';
import 'package:member360/core/requester/consumer/requester_consumer.dart';
import 'package:member360/core/theme/colors/colors_extension.dart';
import 'package:member360/core/theme/text/app_text_style.dart';
import 'package:member360/core/widgets/GenericTextField.dart';
import 'package:member360/core/widgets/custom_calendar/custom_calendar_timeline.dart';
import 'package:member360/core/widgets/failure_view_widget.dart';
import 'package:member360/features/base/data/models/class_model/class_model.dart';
import 'package:member360/features/base/data/models/date_model/date_model.dart';
import 'package:syncfusion_flutter_calendar/calendar.dart' as syncf;

import '../../../../../../core/constants/dimens.dart';
import '../../../../../../core/routes/router_imports.gr.dart';
import '../../../../../../core/widgets/CachedImage.dart';
import '../../../../../../core/helpers/validator.dart';
import '../../../../../../core/widgets/custom_indicator.dart';
import '../../../../../../core/widgets/shimmers/circle_shimmer.dart';
import '../../../../../../core/widgets/shimmers/text_shimmer.dart';
import '../../../../../../res.dart';
import '../../../widgets/build_custom_sheet_item.dart';
import '../calendar_imports.dart';

part "build_scrollable_calendar.dart";
part "calendar_app_bar.dart";
part "build_calendar_filter.dart";
part "build_class_card.dart";
part "build_class_pt.dart";
part "calendar_class_list.dart";
// part 'calendar_session_list.dart';
part "build_choose_gym.dart";
part "build_choose_trainer.dart";
part "build_choose_tag.dart";
part "build_trainer_warning.dart";
part "build_empty_list.dart";
part "calendar_class_loading.dart";
part "test.dart";
// part "calendar_session_list.dart";