/// Generated by AssetsRefGenerator on 2022/03/09
class Res {
  static const String errorSnackBar = "assets/images/error_snack_bar.svg";
  static const String warningSnackBar = "assets/images/warning_snack_bar.svg";
  static const String successSnackBar = "assets/images/success_snack_bar.svg";

  static const String avatarSolidLogo = "assets/images/avatar_solid_logo.png";
  static const String apple = "assets/images/apple.svg";
  static const String ar = "assets/lang/ar.json";
  static const String arrow = "assets/images/arrow.svg";
  static const String en = "assets/lang/en.json";
  static const String facebook = "assets/images/facebook.svg";
  static const String icon = "assets/images/icon.png";
  static const String logo = "assets/images/logo.png";
  static const String logoSvg = "assets/images/logoSvg.svg";
  static const String marker = "assets/images/marker.png";
  static const String email = "assets/images/email.png";
  static const String password = "assets/images/password.png";
  static const String offline = "assets/images/offline.png";
  static const String appLoaderBg = "assets/images/appLoaderBg.png";
  static const String background = "assets/images/background.png";
  static const String phone = "assets/images/phone.png";
  static const String home = "assets/images/home.png";
  static const String profile = "assets/images/profile.png";
  static const String calendar = "assets/images/calendar.png";
  static const String avatar = "assets/images/avatar.png";
  static const String gym = "assets/images/gym.png";
  static const String trainer = "assets/images/trainer.png";
  static const String noTrainer = "assets/images/no_trainer.png";
  static const String empty = "assets/images/empty.png";
}
